name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'index.html'
  pull_request:
    branches: [ main ]
    paths:
      - 'index.html'

jobs:
  deploy-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install perl
        run: sudo apt-get install -y perl

      - name: Replace firebaseConfig in index.html
        run: |
          cp index.html index.deploy.html
          perl -0777 -i -pe "s|const firebaseConfig\s*=\s*\{.*?\};|const firebaseConfig = { apiKey: '${{ secrets.FIREBASE_API_KEY }}', authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}', projectId: '${{ secrets.FIREBASE_PROJECT_ID }}', storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}', messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}', appId: '${{ secrets.FIREBASE_APP_ID }}', measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}' };|s" index.deploy.html

      - name: Copy index.deploy.html to server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          scp -i private_key -o StrictHostKeyChecking=no index.deploy.html $SERVER_USER@$SERVER_HOST:$SERVER_PATH/index.html
          rm private_key
